version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: webextractor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: webextractor
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: webextractor_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webextractor_api
    environment:
      ConnectionString: "Host=db;Port=5432;Database=webextractor;Username=postgres;Password=;"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:80"
    ports:
      - "8090:80"
    volumes:
      - .:/src
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data: